import { pgTable, serial, text, integer, timestamp, index, uniqueIndex, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { mediaFilesTable } from "./media_files";

// A collection is a virtual grouping of media files. Kinds:
//   auto   — generated by the auto-album engine (events, places, doc categories)
//   smart  — user-defined rule, evaluated at query time (never materialized)
//   manual — user-created album with explicitly added items
// Favorites are NOT a collection row: they live as media_files.favorite and are
// surfaced as a virtual, always-available collection by the API.
export const collectionsTable = pgTable("collections", {
  id:          serial("id").primaryKey(),
  nasPath:     text("nas_path").notNull(),
  kind:        text("kind").notNull(), // auto | smart | manual
  name:        text("name").notNull(),
  description: text("description"),
  // Stable identity for auto albums (e.g. "event:2024-06", "place:46.95,7.44",
  // "doc:receipts") so rebuilds update rather than duplicate, and user renames
  // survive rebuilds.
  autoKey:     text("auto_key"),
  // Marks an auto album the user deleted; rebuilds must not resurrect it.
  removedAt:   timestamp("removed_at"),
  // Smart folder rule (JSON) — see SmartRule in the API layer.
  ruleJson:    jsonb("rule_json"),
  coverFileId: integer("cover_file_id"),
  createdAt:   timestamp("created_at").notNull().defaultNow(),
  updatedAt:   timestamp("updated_at").notNull().defaultNow(),
}, (t) => [
  uniqueIndex("collections_nas_auto_key_unique").on(t.nasPath, t.autoKey),
  index("collections_nas_kind_idx").on(t.nasPath, t.kind),
]);

export const collectionItemsTable = pgTable("collection_items", {
  id:           serial("id").primaryKey(),
  collectionId: integer("collection_id").notNull().references(() => collectionsTable.id, { onDelete: "cascade" }),
  mediaFileId:  integer("media_file_id").notNull().references(() => mediaFilesTable.id, { onDelete: "cascade" }),
  addedAt:      timestamp("added_at").notNull().defaultNow(),
}, (t) => [
  uniqueIndex("collection_items_unique").on(t.collectionId, t.mediaFileId),
  index("collection_items_file_idx").on(t.mediaFileId),
]);

export const insertCollectionSchema = createInsertSchema(collectionsTable).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertCollection = z.infer<typeof insertCollectionSchema>;
export type Collection = typeof collectionsTable.$inferSelect;
export type CollectionItem = typeof collectionItemsTable.$inferSelect;